### ISSUE TITLE
Detecting pre-init device on an already rooted phone (no spare specimen, "main" phone in use) problem/concern

### ISSUE THREAD

**Issue by oddgirl** [chenxiaolong/avbroot#113]
Hi! long story short I don't have a spare device for tests and am a bit wary updating the magisk app without proper OTA update

BUT I can't update to latest magisk "boot image wise" because it wants me to specify the pre-init partition

which I do not know and in order to find out I'd need to update magisk.apk (without new boot.img) then perform a test patching (as specified by readme) and then do proper OTA patch and update

Needless to say this spooks me immensely because it feels like something important may get broken

Is installing latest magisk with a "slightly :) " out of date boot.img known-safe?

**Comment by chenxiaolong** [comment]
> Is installing latest magisk with a "slightly :) " out of date boot.img known-safe?

Yep! That should be perfectly fine. Updating the app prior to `boot.img` is what non-avbroot users would do too :)

Even if the Magisk app was broken or uninstalled, the device should still boot and `su` would still continue to operate with the previously configured Magisk settings.

> then perform a test patching (as specified by readme) and then do proper OTA patch and update

By test patching, are you referring to this part of the README?

> If it's not possible to run the Magisk app on the target device (eg. device is currently unbootable), patch and flash the OTA once using `--ignore-magisk-warnings`, follow these steps, and then repatch and reflash the OTA with `--magisk-preinit-device <name>`.

If so, then you won't need to go through the trouble of two flashes. Since you have a working setup already, you can install the new Magisk apk and follow the steps at https://github.com/chenxiaolong/avbroot#magisk-preinit-device to find the preinit device and then do the proper patch with `--magisk-preinit-device <name>`.
