### ISSUE TITLE
Custom kernel

### ISSUE THREAD

**Issue by powellnorma** [chenxiaolong/avbroot#13]
Hey, I think the kernel is embedded in the boot.img. As avbroot already seems to patch this image, it would be nice if we could add an option like `--custom-kernel <path>`, which then would replace the existing kernel with the one specified. What do you think? And is the kernel zImage signed too, or only the boot.img?

**Comment by powellnorma** [comment]
Having looked into it a bit, I think we could clone `MagiskRootPatch` to `CustomKernelPatch`, and let that class use `abootimg -u` - Would that be fine?

**Comment by powellnorma** [comment]
For the record, I tried to do this (see [this branch](https://github.com/powellnorma/avbroot/tree/custom_kernel)), but the system did not boot afterwards ("error boot prepare") - Not even booting into recovery was possible (fastboot still worked though). The kernel I tried to flash was [this one](https://github.com/engstk/pxl4a). If anyone has an idea what may have gone wrong, I'd be very grateful!

**Comment by powellnorma** [comment]
Hm, I guess we would have to run the AnyKernel3 Script that is contained in the .zip - However that seems to assume it is being run on the device itself. Do you have an idea how one could workaround this, so that one can use a custom AK3 and still maintain Android Verified Boot? I guess one could dd the new boot partition from the running device, run avb

**Comment by chenxiaolong** [comment]
> Hey, I think the kernel is embedded in the boot.img.

Yep, that should be the case on every device. However, avbroot only patches the boot image that contains the ramdisk holding `/init`. On devices launching with Android >=13, `boot` wouldn't be touched because the ramdisk lives in `init_boot`.

> And is the kernel zImage signed too, or only the boot.img?

The entire image is signed as a whole.

> the system did not boot afterwards ("error boot prepare") - Not even booting into recovery was possible

Unfortunately, debugging issues like this is painful on newer devices. On older devices, you used to be able to reboot into recovery and look at the logs in `/proc/last_kmsg` or `/sys/fs/pstore`. On newer devices, both the regular system and recovery use the same kernel, so that's no longer possible.

> it would be nice if we could add an option like `--custom-kernel <path>`, which then would replace the existing kernel with the one specified. 

I probably won't end up adding this as a feature unless there's a way it can be easily done universally. On older devices (before Pixel 6, I think), simply replacing the kernel image is good enough. On newer devices, Android uses separate `.ko` kernel modules that live on a different partition that'd also need to be replaced. Those partitions are regular filesystems (eg. ext2) that require dm-verity, which complicates the signing procedure.

That said, I'm still happy to help try and get this working for you!

To rule out abootimg being an issue, I'd suggest trying to use magiskboot to do the boot image unpacking/repacking:

```python
class CustomKernelPatch(BootImagePatch):
    '''
    Replace the kernel within the boot image.
    '''
    
    EXTRACT_MAP = {
        'lib/x86/libmagiskboot.so': {'dest': 'magiskboot'},
    }
    
    def __init__(self, magisk_apk, custom_kernel):
        super().__init__(magisk_apk, self.EXTRACT_MAP)
        self.custom_kernel
        
    def patch(self, image_file, temp_dir):
        def run(*args):
            subprocess.check_call(['./magiskboot', *args], cwd=temp_dir)
            
        os.chmod(os.path.join(temp_dir, 'magiskboot'), 0o755)
        
        # Unpack the boot image
        run('unpack', image_file)
        
        # Replace the kernel image
        shutil.copyfile(self.custom_kernel, 'kernel')
        
        # Repack image
        run('repack', image_file)
        
        shutil.copyfile(os.path.join(temp_dir, 'new-boot.img'), image_file)
```

> Hm, I guess we would have to run the AnyKernel3 Script that is contained in the .zip - However that seems to assume it is being run on the device itself. Do you have an idea how one could workaround this, so that one can use a custom AK3 and still maintain Android Verified Boot?

I haven't heard of AnyKernel3 before, but taking a brief look at the script, it seems to be used to add files to the ramdisk (the `ramdisk` folder in the zip in this case). That's something you could do in avbroot as another patch (similar to `OtaCertPatch`).

> I guess one could dd the new boot partition from the running device, send it to computer, and resign it with avbtool there?

Yes, that'd technically work, though I'd caution against doing that. If the bootloader is locked and an unsigned boot image is (temporarily) flashed to the boot partition, then an accidental reboot will leave the device unbootable. (and unlocking the bootloader + wiping data would be required to get back to a working state)

I'd suggest first getting the kernel to boot without any ramdisk changes though. The ramdisk changes seem to only perform certain tweaks (like changing the scheduler) during boot. Once the kernel boots, then you can deal with these additional changes.

**Comment by powellnorma** [comment]
> To rule out abootimg being an issue

I have incorporated your snippet on [this branch](https://github.com/powellnorma/avbroot/tree/custom_kernel), and it works now, thank you! :)

> Yes, that'd technically work, though I'd caution against doing that.

I understand the risk, but I am still interested in what the procedure would look like. I guess something like this?

1. `avbtool erase_footer --image boot.img`
2. `avbtool add_hash_footer --image boot.img --partition_name boot --partition_size ?? --key key.pem --algorithm SHA256_RSA4096`

The partition size is just the file size I assume (the file being created via `dd if=/dev/block/by-name/boot_b of=boot.img`)? Would these commands likely be enough?

> On newer devices, Android uses separate .ko kernel modules that live on a different partition that'd also need to be replaced

The stock Image I used before also came with .ko modules (and they are still there at `/vendor/lib/modules/`), but the custom kernel was build in such a way that they are already included.

The repository https://github.com/osm0sis/AnyKernel3 seems to document the structure of AK3 .zip Archives. Since it looks like the files that would need to be patched/added are always on predetermined places (/ramdisk, /modules/system/lib/modules), I think it would (in theory) be possible to add a rudimentary support for AK3 .zip archives to avbroot. On the other side it looks like AK3 supports custom scripting/hooking, and that would get lost this way

**Comment by chenxiaolong** [comment]
> I have incorporated your snippet on [this branch](https://github.com/powellnorma/avbroot/tree/custom_kernel), and it works now, thank you! :)

Great!

> I understand the risk, but I am still interested in what the procedure would look like. I guess something like this?
>
> 1. `avbtool erase_footer --image boot.img`
> 2. `avbtool add_hash_footer --image boot.img --partition_name boot --partition_size ?? --key key.pem --algorithm SHA256_RSA4096`
>
> The partition size is just the file size I assume (the file being created via `dd if=/dev/block/by-name/boot_b of=boot.img`)? Would these commands likely be enough?

There are two ways that AVB can verify the boot image:

1. The `boot.img` has an unsigned footer and the checksum of the image is placed inside `vbmeta.img`.
2. The `boot.img` has a signed footer and the public key used to verifying it is stored inside `vbmeta.img`.

You can check which one your firmware uses by running:

```
avbtool info_image --image vbmeta.img
```

If you see a hash descriptor for the `boot` partition, then AVB is using method 1:

```
    Hash descriptor:
      Image Size:            <size> bytes
      Hash Algorithm:        sha256
      Partition Name:        boot
      Salt:                  <salt>
      Digest:                <checksum>
      Flags:                 0
```

If you see a chainload descriptor for the `boot` partition, then AVB is using method 2:

```
    Chain Partition descriptor:
      Partition Name:          boot
      Rollback Index Location: <number>
      Public key (sha1):       <public key checksum>
```

If the firmware uses method 1, you'll have to regenerate `vbmeta.img` so that it contains the new `boot.img` checksum. That is very painful to do with `avbtool`'s command line because you have to manually specify everything in `avbtool info_image --image vbmeta.img`. In this scenario, it'd be way easier to add another patch to avbroot for completely replacing `boot.img`.

If the firmware uses method 2, your second step is correct for the signing part. `boot` itself is signed and the public key inside the existing `vbmeta` is still valid. However, where you'll run into trouble is the `erase_footer` step. The way it works is that it just truncates the file to the `Original image size` value mentioned in `avbtool info_image --image boot.img`. AnyKernel3 does not touch the footer, so that field very likely has the wrong size after its patches have been applied. You can use something like https://gist.github.com/chenxiaolong/fac7dca73065a6b82d426cb9bb5a80db to calculate the size of the actual data from the boot image header and then do `truncate -s <size> boot.img` to truncate any excess data (including the old footer).

Regarding the `--partition_size` option, the value should indeed be the size of the file created by `dd`. However, to be extra sure, you can run `avbtool info_image --image boot.img` against an unmodified boot image and look at the `Image size` field (which is exactly the value passed to `--partition_size` when that image was initially built).

> The stock Image I used before also came with .ko modules (and they are still there at `/vendor/lib/modules/`), but the custom kernel was build in such a way that they are already included.

Interesting. I wonder if they just build them into the kernel and ignore the existing `.ko` modules.

**Comment by powellnorma** [comment]
Thank you again for your help! :)

> I wonder if they just build them into the kernel and ignore the existing .ko modules

I think so, it looks like even the ability of the kernel to load modules was removed: https://github.com/engstk/pxl4a/pull/8
Afaik there is nothing that stops one from inlining any module at build time, it's just that the kernel image gets a bit bigger.

I will close this issue for now, in case that I later add a patch to avbroot that allows to resign an existing boot.img, I will share it with you
