### ISSUE TITLE
"The system cannot find the path specified" when patching OTA.zip

### ISSUE THREAD

**Issue by MattStager** [chenxiaolong/avbroot#15]
Hello, any chance I can get some help with this message that I'm receiving when trying to patch the OTA zip:

` python avbroot.py patch --input ota.zip --privkey-avb avb.key --privkey-ota ota.key --cert-ota ota.crt --magisk magisk.apk
Traceback (most recent call last):
  File "C:\Users\Matt\avbroot\avbroot.py", line 308, in <module>
    main()
  File "C:\Users\Matt\avbroot\avbroot.py", line 300, in main
    patch_subcommand(args)
  File "C:\Users\Matt\avbroot\avbroot.py", line 213, in patch_subcommand
    with tempfile.TemporaryDirectory(dir='/dev/shm') as key_dir:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\tempfile.py", line 819, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\tempfile.py", line 368, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/dev/shm\\tmp5w4bfcly'`

**Comment by chenxiaolong** [comment]
This should be fixed by #16. I accidentally added a "Linux'ism" to the code. Can you `git pull` and try again?

**Comment by MattStager** [comment]
Thanks, I'll give it a go this weekend

**Comment by ArtemPisarenko** [comment]
#16 and #18 will not solve this issue. avbroot runs magisk executables from provided apk file which can't be run on any platform different from linux x86. Furthermore, even on linux x86 it's a hack which works thanks to a luck (because [officially](https://github.com/topjohnwu/Magisk/issues/2859#issuecomment-638039682) magisk doesn't support running its utilities outside of android system). I would document in README that only linux supported, because people see python implementation and mistakenly believe that it can be run anywhere where python does.

**Comment by ArtemPisarenko** [comment]
Although, one may [try](https://github.com/topjohnwu/Magisk/issues/2859#issuecomment-638149653) to run via WSL2

**Comment by chenxiaolong** [comment]
Thanks @ArtemPisarenko. I completely forgot that magiskboot is Linux-only. I'll update the README.

In the future, I might update the project to run magiskboot inside a qemu-aarch64 VM with an Android kernel + minimal userspace.

**Comment by chenxiaolong** [comment]
As of #37, avbroot no longer uses magiskboot and now runs on Windows natively.
