### ISSUE TITLE
dumb guy question, but is this easily reversible to stock and vendor avb keys

### ISSUE THREAD

**Issue by adrianmmiller** [chenxiaolong/avbroot#194]
Nowhere does the README state this is reversible...

What if any steps should be documented

**Comment by chenxiaolong** [comment]
Oh, good point, I'll update the README to include that.

Everything is completely revertible just by unlocking the bootloader, clearing out the custom key with `fastboot erase avb_custom_key`, and then flashing the stock firmware.

**Comment by adrianmmiller** [comment]
> Oh, good point, I'll update the README to include that.
> 
> Everything is completely revertible just by unlocking the bootloader, clearing out the custom key with `fastboot erase avb_custom_key`, and then flashing the stock firmware.

Thanks mate!

**Comment by chenxiaolong** [comment]
> I am curious what will happen when someone flashes stock ROM and relocks bootloader without clearing custom AVB keys. I found some info here but not sure.

If you flash the stock ROM, but don't clear the custom AVB key, the bootloader will not allow the device to be relocked (thanks to pascallj for testing this in #7). I think this is done as a precaution so the user doesn't accidentally do the wrong thing.

However, the documentation is correct in that the bootloader technically will trust both your custom key and the built-in Google key. If the bootloader is already locked and you're running a custom signed OS, and you try to manually flash the stock OS via root access, the device will still boot because both keys are trusted.

**Comment by chenxiaolong** [comment]
I don't think the bootloader supports that, unfortunately. The only way to know if the current key is correct is to try booting.
