### ISSUE TITLE
[Question] Is patching possible?

### ISSUE THREAD

**Issue by heckarman** [chenxiaolong/avbroot#248]
So, I daily drive GrapheneOS with unlocked bootloader and rooted with Magisk.  
Is it possible to patch the OTA without actually changing the `avb_custom_key`? I would want to use the key given by GrapheneOS given that wiping data and stuff is a huge pain (at least, in my case) if I signed the OTA with my own custom key.  

Or is it possible that I patch the OTA with my own key (of course, I'm not willing to lock the bootloader as it wipes the data and it takes me a day to set it up) to install KernelSU properly, and receive OTA from Official GrapheneOS in future? 

Or am I missing anything here? I'm aware that this repo i.e., avbroot is not a small project but rather gigantic learning library on its own. So asking.

Thanks in advance.

**Comment by chenxiaolong** [comment]
> So, I daily drive GrapheneOS with unlocked bootloader and rooted with Magisk.
> Is it possible to patch the OTA without actually changing the `avb_custom_key?` I would want to use the key given by GrapheneOS given that wiping data and stuff is a huge pain (at least, in my case) if I signed the OTA with my own custom key.

I might not be fully understanding what you're asking here. Given that your bootloader is currently unlocked, all verification is disabled (and `avb_custom_key` is ignored). There wouldn't really be a point in adding avbroot to the mix with this setup, but it definitely would boot just fine.

> Or is it possible that I patch the OTA with my own key (of course, I'm not willing to lock the bootloader as it wipes the data and it takes me a day to set it up) to install KernelSU properly, and receive OTA from Official GrapheneOS in future?

As soon as you make any modifications, like flashing a KernelSU boot image, you can't use the official OTAs anymore. The incremental OTAs will likely fail to install and the full OTAs from GrapheneOS' website would overwrite the kernel with what GrapheneOS ships.

> Or if I somehow manage to lock the bootloader with my custom key with kernelSU (given that it is better than Magisk in terms of security and the likes), can I patch the ota automatically with GitHub CI (I believe it is possible and easier to implement) such that every OTA generated is published as a release and the system updater fetches the new release from the release section rather than checking from official grapheneOS (This might require core level change, so I might go with Custota and point it to github release if that's supported similar to how obtanium work)?

Yep, this would likely work quite well. I'm not sure if Github releases can store files as large as a GrapheneOS OTA, but the Actions workflow could always upload the result to some other server.

I'm biased since I wrote Custota, but I'd definitely recommend it if you want automatic updates from a custom OTA server. GrapheneOS' builtin updater hardcodes the URL and TLS certificate for certificate pinning. If you want to use the builtin updater, you'd have to modify the source code, build a new apk, and then use a Magisk/KernelSU module to override the original apk.

**Comment by chenxiaolong** [comment]
> I'm afraid regarding installing modules day PI fix and etc that might end up device being bricked.

https://kernelsu.org/guide/rescue-from-bootloop.html#rescue-by-pressing-volume-down would probably help if a module were to cause issues. I believe Magisk has the exact same feature too.

> how I can patch an existing kernel in a way similar to patching boot img

This would be incredibly difficult (if it's even possible at all). If the prebuilt kernels they provide aren't compatible, then compiling the GrapheneOS kernel from source with KernelSU integrated is probably the only way to do it.

**Comment by probablypablito** [comment]
Just tried this today (GrapheneOS with avbroot + KernelSU). It seems that KernelSU doesn't work on GrapheneOS, at least with the default kernel. I went through the process twice, once patching boot.img manually using `ksud` and another patching using the KernelSU app on the phone directly. Neither worked. I'll look into compiling the kernel (and I'll publish it if I manage to automate it), but it definitely seems like a learning experience 🥲

**Comment by chenxiaolong** [comment]
Yep, KernelSU's kernel module method will never work on GrapheneOS because GrapheneOS requires all kernel modules to be signed: https://github.com/GrapheneOS/kernel_common-6.1/commit/7995bdedfaa485c168fa6227326b550e5cd77f18. To make the kernel trust your own signing key, you have to compile the kernel yourself. At that point, it makes the most sense to just apply KernelSU's patches and avoid using a module.
