### ISSUE TITLE
Possibility of patching certain files in system image?

### ISSUE THREAD

**Issue by Sadoon-AlBader** [chenxiaolong/avbroot#250]
My use case is basically changing a font in a system.img, I've found that it's impossible to mount it `-o rw` and change files. Is this possible?
I've seen in #239 that it is possible to change files in boot.img, was hoping system.img is also doable :)

**Comment by chenxiaolong** [comment]
avbroot, as of version 3.0.0, does modify `system.img` to replace the `/system/etc/security/otacerts.zip` file, but the implementation is not really useful for other modifications.

To replace a file, there are many requirements:

* The file size must be smaller than 4 KiB
* The new file must be exactly the same size as the old file
* It must be possible to find the exact byte location of the old file in `system.img` based on the fiie's contents alone (so no searching based on filename or path)

These requirements exist because avbroot doesn't actually understand filesystems, like ext4/f2fs/erofs. It's directly replacing bytes in `system.img` that just happens to work for these filesystems.

---

The ideal way to make modifications it to mount `system.img` as r/w and then patch the OTA with the `--replace system modified.img` option. This is possible if `system.img` is formatted with ext4 or f2fs.

If it's formatted with a read-only filesystem, like erofs, then the next best option is probably to create a Magisk/KernelSU module instead of trying to modify `system.img`.
