### ISSUE TITLE
For Xiaomi Device Systerm Verify failed.

### ISSUE THREAD

**Issue by qianmo-xw** [chenxiaolong/avbroot#280]
[    1.613176] init: [libfs_avb]Returning avb_handle with status: Success
[    1.613538] init: [libfs_avb]: Error verifying vbmeta image: OK_NOT_SIGNED
[    1.613550] init: [libfs_avb]Found unknown public key used to sign /system
[    1.613554] init: [libfs_avb]Returning avb_handle for '/system' with status: VerificationError

I already use fastboot flash avb_custom_key，Have any possible to solve it？

it not report boot unsigned，Just System.

Device：XiaoMi Pad6 Pro

If you need OTA package，download from https://xiaomirom.com/rom/xiaomi-pad-6-pro-liuqin-china-fastboot-recovery-rom/

I don't know if Xiaomi doesn't accept third-party signatures, or if the system signature failed during the signing process

**Comment by qianmo-xw** [comment]
Found unknown public key used to sign /system  mean  not  accept third-party signatures？

**Comment by pixincreate** [comment]
From what I know, no, xiaomi does not allow custom signatures. Trying to lock bootloader with custom AVB Key might end you up bricking the device.

The devices that allows lockable bootloaders with custom keys are Google Pixels and few OnePlus phones

**Comment by qianmo-xw** [comment]
> From what I know, no, xiaomi does not allow custom signatures. Trying to lock bootloader with custom AVB Key might end you up bricking the device.
> 
> The devices that allows lockable bootloaders with custom keys are Google Pixels and few OnePlus phones

f**k xiaomi.It would be great if it could support custom signatures. This is the only device I have found that won't be tee damaged so far

**Comment by qianmo-xw** [comment]
> No, they wouldn't. In fact, with HyperOS (Xiaomi's latest OS for Android), they made it much more harder for users to unlock bootloader. So there's no hopes left.

oh,I know,maybe I need to find a new device support unlock bootloader  and tee not damaged. As far as I know only xiaomi device will not be tee damaged.....

**Comment by pixincreate** [comment]
Even you say "will not be tee damaged.....", can you elaborate that? 

I assume you previously used a Samsung device, unlocked it's bootloader that blowed up the Knox fuse.

**Comment by qianmo-xw** [comment]
> Even you say "will not be tee damaged.....", can you elaborate that?
> 
> I assume you previously used a Samsung device, unlocked it's bootloader that blowed up the Knox fuse.

trusted execution environment   is  be called tee, some banking software will detect this, WeChat will not be able to use fingerprints, Netflix clarity will be damaged, presumably so, you can use the momo app to detect whether it is damaged.

**Comment by pixincreate** [comment]
From what I remember, if the bootloader is unlocked, then Momo used to tell at the user saying TEE is broken which could easily be overridden by spoofing.

**Comment by chenxiaolong** [comment]
Yep, as far as I'm aware, Xiaomi's bootloaders do not actually allow custom keys, even if `fastboot flash avb_custom_key` happens to work. Unfortunately, there's nothing you can do to make avbroot work on your device.

**Comment by admin-elvistrujanovic** [comment]
But if boot.img got passed successfuly just not /system - maybe it's not because it doesn't accept third party certificates. Maybe OS itself doesn't accept third-party certificates even if bootloader itself accepts them. To bypass this you can try to replace public OEM key from /system partition with your custom one (keeping the same file name of the public key), patch vbmeta with disable signature option and sign images you've patched with your own certificate.

After that, do not yet lock bootloader but first wipe all data on your device and boot immediatelly to fastboot mode, to avb_custom_key commands and then flash modified system. Also, search for other partitions like dtbo and so on so if you find there Xiaomi's/Qualcom's public key, replace it with your own and resign those images.

Do now booting into recovery mode, clear caches, boot into normal mode, complete set up, install Key Attestation from github (latest version), install it and if it says selfsigned somwhere (even if it reports that bootloader is unlocked), please let us know.

Now reboot your device again into bootloader/fastboot mode, relock the bootloader, boot into recovery mode, clear caches and reboot system.


If someone are willing to try this, please let us know did your device booted successfuly and send boot logs for future investigation.

**Comment by admin-elvistrujanovic** [comment]
@qianmo-xw So what you think - are you capable of trying this method?
