### ISSUE TITLE
Not able to patch OTA, failed to create temp file

### ISSUE THREAD

**Issue by RickMarijn** [chenxiaolong/avbroot#325]
When I try to patch an OTA file with the following command: 
`./avbroot ota patch \
    --input /home/rm/Downloads/avbroot/avbroot-3.4.1-aarch64-linux-android31/shiba-ota_update-2024072800.zip \
    --key-avb /home/rm/Downloads/avbroot/avbroot-3.4.1-aarch64-linux-android31/avb.key \
    --key-ota /home/rm/Downloads/avbroot/avbroot-3.4.1-aarch64-linux-android31/ota.key \
    --cert-ota /home/rm/Downloads/avbroot/avbroot-3.4.1-aarch64-linux-android31/ota.crt \
    --magisk /home/rm/Downloads/avbroot/avbroot-3.4.1-aarch64-linux-android31/Magisk-v27.0.apk \
    --magisk-preinit-device sda10`
It spits out the following error and I can't seem to figure out why

`5.966s  INFO Replacing zip entry: META-INF/com/android/otacert
5.986s  INFO Copying zip entry: apex_info.pb
5.986s  INFO Copying zip entry: care_map.pb
5.987s  INFO Patching zip entry: payload.bin
6.148s  INFO Extracting from original payload: system
6.243s ERROR Failed to patch OTA zip
Caused by:
    0: Failed to patch payload: payload.bin
    1: Failed to create temp file for: system
    2: No such file or directory (os error 2)`

**Comment by chenxiaolong** [comment]
Hmm, seeing `/home` in the path, it sounds like you might be running the Android avbroot binary on a regular (non-Android) Linux system. The problem with that is the default temp directory on Linux is `/tmp`, but on Android, it's `/data/local/tmp`, which likely doesn't exist on your system.

If you override the temp directory location with:
```
export TMPDIR=/tmp
```
before running a avbroot, then it should work.

**Comment by pascallj** [comment]
Just want to verify something: are you running avbroot on Android? The name of your working directory (`avbroot-3.4.1-aarch64-linux-android31`) suggests that you extracted the android zip (which is intended to be run on Android) and are therefore using the avbroot Android binary. However the path you showed (`/home/$USER/Downloads`) implies that you are running a regular Linux-like system. Or are you using the Android binary because you are on ARM?

If you are running on Linux, make sure you use the `avbroot-[version]-x86_64-unknown-linux-gnu.zip` avbroot binary and see if that solves your problem.

**Comment by RickMarijn** [comment]
I am running avbroot on a Fedora Linux system. I'll try the x86 binary. Thanks

**Comment by RickMarijn** [comment]
Should I generate new keys for the x86 binary?

**Comment by RickMarijn** [comment]
Alright, the incorrect binary fixed my issue. Closing.
