### ISSUE TITLE
Disabling OEM unlocking when using a patched OTA with rootless flag

### ISSUE THREAD

**Issue by keonly** [chenxiaolong/avbroot#330]
Hello, I have a question about the OEM unlocking option when using avbroot with `--rootless` flag.

In [Warnings and caveats](https://github.com/chenxiaolong/avbroot?tab=readme-ov-file#warnings-and-caveats) it says to 'Always leave the OEM unlocking checkbox enabled when using a locked bootloader with root.' Would this mean that if I am using avbroot without root by patching an OTA with `--rootless` flag, I can safely disable OEM unlocking without making my device unbootable?

Thank you for this amazing tool! :)

**Comment by pixincreate** [comment]
It is recommended to it disable OEM unlocking button just because, if tomorrow anything goes wrong you'll have an option to recover your device by unlocking the bootloader at the cost of userdata.  

It is just a toggle that enables bootloader unlocking. Nothing much to deal with security as it alone cannot provide a way to access any data from what I know.

**Comment by pixincreate** [comment]
If you're just planning to sign the OTA with your keys, then I do not find any issues, but if you're planning to inject modules with [afsr](https://github.com/chenxiaolong/afsr) by following or [my-avbroot-setup](https://github.com/chenxiaolong/my-avbroot-setup) or [PixeneOS](https://github.com/pixincreate/PixeneOS) (still in early stage BTW), you'll have to keep it disabled as new OTAs tend to break modules due to compatibility issues.

**Comment by chenxiaolong** [comment]
Glad you like avbroot!

I'd recommend leaving OEM unlocking always enabled, even if you're running an unrooted OS.

Unexpected things can happen. For example, recently, some folks got stuck with hard bricked devices, even on the (unmodified) stock OS: https://issuetracker.google.com/issues/350285633. This can't happen if OEM unlocking is enabled as you'd have a way to recover.

The risk you take by leaving the option enabled is if there's a bootloader bug that prevents it from properly wiping the user data when unlocking the bootloader again. I personally think that's a very small risk.

**Comment by keonly** [comment]
Thank you all for the comments! I should just leave it toggled enabled just to be safe as your recommendations. Closing the issue.
