### ISSUE TITLE
Validation error: Unsupported Magisk version

### ISSUE THREAD

**Issue by JedaiRussia** [chenxiaolong/avbroot#389]
Full text of the error: `Validation error: Unsupported Magisk version 28100 (supported: [25102..25207, 25211..28100])`
Should version 28100 actually be supported?

**Comment by chenxiaolong** [comment]
In the error message, the ranges are half-open intervals, so numbers to the right of `..` are not included. (I'll be improving the error message in the next release.)

Magisk 28100 is not supported because I haven't had a chance to look over the changes and personally test it yet. However, it's pretty unlikely that there are any compatibility issues, so if you'd prefer not to wait, you can patch with `--ignore-magisk-warnings`.

**Comment by JedaiRussia** [comment]
Thanks for the explanation, I understand. And thank you for what you do!
