### ISSUE TITLE
Error in /sideload/package.zip

### ISSUE THREAD

**Issue by ShockedCoder** [chenxiaolong/avbroot#393]
OS: CalyxOS
Device: Fairphone 5
Magisk: v28.1

Was working just fine before I updated from v28 to v28.1 using Custota
Magisk complained about "Wrongfully installed ROM, repatch it"

Tried to sideload previous OTA patch, got this:
```
Now send the package you want to apply
to the device with "adb sideload <filename>"...
Supported API: 3
Finding update package...
Verifying update package...
Update package verification took 68.0 s (result 0).
Installing update...
Step 1/2
Error applying update: 7 (ErrorCode::kInstallDeviceOpenError)
ERROR:   recovery: Error in /sideload/package.zip (status 1)

Install from ADB completed with status 1.
Installation aborted.
```
After this invalid install, I got a warning in red above the menu, but below the yellow text:
```
WARNING: Previous installation has failed.
  Your device may fail to boot if you reboot or power off now.
```

This happens when I try to install both the v28 and the v28.1 OTA patch
Both OTA versions are the same, the magisk versions are the only difference

**Comment by chenxiaolong** [comment]
Huh, that's interesting. avbroot 3.9.0 and 3.10.0 should've both produced identical output files (same checksum and everything). Anyway, glad it's working for you now!

**Comment by chenxiaolong** [comment]
Yeah sure. Happy to take a look and compare them.

**Comment by chenxiaolong** [comment]
There are 2 partitions in those OTAs that are different: `boot` and `vbmeta`. (`vbmeta` is only different because it contains the signature of `boot`, which was different.)

Inside `boot`, there are 2 differences:
* The bad OTA has `.backup/init`, while the good OTA has a compressed `.backup/init.xz`
* The good OTA has `PREINITDEVICE=sda15` in the Magisk config file, but the bad OTA does not

Were both of these patched via the Magisk app? Any chance you still have the exact commands that produced these OTAs?

---

However, with that said...

The weird thing is that none of those differences matter at all while flashing. The flashing process doesn't care about the contents of the partitions. It only cares that the checksums and signatures are valid. And from what I can tell, they're perfectly valid in both the bad and good OTAs.

If this happens again in the future, please try grabbing the recovery logs before rebooting. If CalyxOS recovery allows adb, then you should be able to do `adb pull /tmp/recovery.log`. Otherwise, you'll have to pick the `View recovery logs` menu option and scroll down with the volume keys until you see the same error code from the sideload output (`ErrorCode::kInstallDeviceOpenError`) and then take a picture.

**Comment by chenxiaolong** [comment]
Ah, thanks for the additional info.

The combo of avbroot 3.9.0 + Magisk 28.1 + `--ignore-magisk-warnings` is definitely the cause of the differences in the two OTAs. The problem is that when the Magisk version is not supported by avbroot, avbroot assumes that Magisk is very old and supports none of the modern Magisk features.

So the `--magisk-preinit-device` got ignored and avbroot assumed that Magisk did not support compression (thus, no `init.xz` file). The missing preinit device is what caused the error you saw:

> Your device needs reflash Magisk to work properly. Please reinstall Magisk within app, recovery mode cannot get correct device info.

The good news is that there's nothing left in a bad state on your device. Once you flash your good OTA, everything is normal again.

(I will fix this bad behavior with unsupported Magisk versions + `--ignore-magisk-warnings` tomorrow.)

---

> I'll try replicating the error when I get home:
>
> 1. Install faulty OTA through Custota
> 2. Do the same through recovery

That would be much appreciated since I still have no idea why any of this would prevent flashing. If you can, please grab `adb logcat -d -s update_engine` after flashing with Custota. That'll make it easy to compare with the recovery log in case there's difference in behavior.

**Comment by chenxiaolong** [comment]
I think the only way is to use another device to take a picture of the screen.
