### ISSUE TITLE
Some questions regarding the implementation details

### ISSUE THREAD

**Issue by pascallj** [chenxiaolong/avbroot#7]
First of all, great work! This seems like an essential step in security by allowing root but keep your device secure (or at least your data) from unwanted modifications by relocking the bootloader. I consider myself lucky to have found this decently new project before I started to use my new Pixel 6a!

I hope you (or someone else) are open to answering some questions about the implementation details. I am aware the issue tracker is not exactly the right place for asking questions, but at least it will keep the discussion public for future reference.

I have been trying to understand each and every part in the implementation and even profiled a run to see what exactly is happening when I am running your tool, but there are still some things which I can't figure out.

First, your implementation seems to be a lot more involved when compared to what the Magisk app does. Would you mind to elaborate on what differences their are? I have for example noticed that you are in fact using `magiskboot` and `boot_patch.sh` from the Magisk app, but also do some extra steps which Magisk doesn't do. Or maybe a general overview of each step and why we need to do that. Could this all be implemented in the Magisk app?

For example, why can't we use the Magisk app to let it patch the boot.img and use avbtool (on PC) via the command line to add the required footers, repack and sign it? Does it have anything to do with the fact that Magisk doesn't touch the vbmeta.img besides disabling verification and integrity?

Is patching `vendor_boot` only necessary to sideload the full OTA or also for some other reason? So in theory if we just flash each partition manually from fastboot (which would be cumbersome), this step should not be needed?

In the comments when patching `vendor_boot` you are mentioning that "a stock OTA will render the device unbootable". Why exactly is this? Isn't the full OTA patching every partition (including vbmeta.img) so all signatures will match and the device will boot just fine? According to [Android Verified Boot 2.0 Readme](https://android.googlesource.com/platform/external/avb/+/master/README.md):
> When the custom key is set and the device is in the LOCKED state it will boot images signed with both the built-in key as well as the custom key

So the custom key shouldn't be a problem here, should it? It still is an undesirable situation though...

Finally, do you mind explaining why we need the `smuggle_descriptors` function? It seems like some black magic to me.

Thank you in advance! :smile:

**Comment by chenxiaolong** [comment]
Sure, happy to answer any questions!

> I have for example noticed that you are in fact using magiskboot and boot_patch.sh from the Magisk app, but also do some extra steps which Magisk doesn't do.

For just the root patch portion, the only thing being done is `boot_patch.sh` ([source](https://github.com/chenxiaolong/avbroot/blob/d0373470b4224d27413c93926957f9d0a03c6a7e/avbroot/boot.py#L33-L61)). The other boot image patch ([source](https://github.com/chenxiaolong/avbroot/blob/d0373470b4224d27413c93926957f9d0a03c6a7e/avbroot/boot.py#L64-L142)) removes the original Google OTA certificate from recovery mode and inserts the user's own OTA certificate so that it's not possible to accidentally flash an original/unpatched OTA. This second patch uses `magiskboot` as a tool for packing/unpacking/manipulating the boot image, but isn't technically relevant to Magisk's root capabilities.

> Could this all be implemented in the Magisk app?

In theory, yes. It would likely have to reimplement most of avbtool, which is not trvial (unless Magisk were to include Python).

> For example, why can't we use the Magisk app to let it patch the boot.img and use avbtool (on PC) via the command line to add the required footers, repack and sign it? Does it have anything to do with the fact that Magisk doesn't touch the vbmeta.img besides disabling verification and integrity?

This is technically possible. The steps would be something like:

1. Patch `boot.img` with magisk
2. Add vbmeta footer to `boot.img` with `avbtool`
3. Build new `vbmeta` image for with `avbtool`

Step 2 can be problematic if done wrong. There are two ways to sign an image in AVB. The image can be directly signed and then the public key is added to `vbmeta` in a chainload descriptor. Or the image can be unsigned and the hash of the image is added to `vbmeta` via a hash descriptor. When the bootloader is locked, if an image ever switches from being verified by a chainload descriptor to a hash descriptor (or vice versa), it will trip the bootloader's rollback protection and leave the device unbootable. It causes the device to deny access to disk encryption keys and the device will be stuck at a message saying that a factory reset is required (at least on my Pixel 6 Pro). avbroot has logic to use chainload or hash descriptors based on which one the original image used.

Step 3 is just tedious. All of the information shown in `avbtool info_image --image vbmeta.img` ([example](https://gist.github.com/chenxiaolong/ef561970914a8095f9283411ede38e12)) needs to be manually replicated in the `avbtool make_vbmeta_image` command. A mistake here either leaves the device unbootable (eg. typo in rollback index) or decreases security (eg. missing chainload or hash descriptor for a partition).

> Is patching `vendor_boot` only necessary to sideload the full OTA or also for some other reason? So in theory if we just flash each partition manually from fastboot (which would be cumbersome), this step should not be needed?

Yes. It's only needed to switch out the OTA certificate used for validating the zip sent by `adb sideload`. Note that `fastboot flash` does not work when the bootloader is locked, even if it's given a properly signed image. An OTA is the only way to update in that scenario.

> In the comments when patching `vendor_boot` you are mentioning that "a stock OTA will render the device unbootable". > Why exactly is this? Isn't the full OTA patching every partition (including vbmeta.img) so all signatures will match and the device will boot just fine? According to [Android Verified Boot 2.0 Readme](https://android.googlesource.com/platform/external/avb/+/master/README.md):
> > When the custom key is set and the device is in the LOCKED state it will boot images signed with both the built-in key as well as the custom key
>
> So the custom key shouldn't be a problem here, should it? It still is an undesirable situation though...

Interesting. I never noticed the "will boot images signed with both the built-in key as well as the custom key" in the documentation. I have not tested to see if that's actually the case on real devices.

Nevertheless, if the documentation is correct and a stock OTA is flashed, it won't be possible to go back to the custom-signed OS without unlocking the bootloader (triggering a data wipe) and flashing the custom patched images again.

> Finally, do you mind explaining why we need the `smuggle_descriptors` function? It seems like some black magic to me.

It is indeed black magic :smile:

When avbroot creates the new `vbmeta` image, it generates new descriptors for the patched `boot`/`init_boot`/`vendor_boot` images. For the rest of the images (eg. `system.img`), it directly copies the descriptor from the original `vbmeta` image. This is an optimization done to improve performance because reading every `.img` to generate new descriptors for every partition is incredibly slow.

The problem is avbtool's Python API does not have a way to simply pass in preexisting descriptors to the `make_vbmeta_image` function. However, the function's `kernel_cmdlines` parameter comes pretty close. For each item in the `kernel_cmdlines` list, it creates an `AvbKernelCmdlineDescriptor` object and adds them to the vbmeta image without doing any further processing ([source](https://android.googlesource.com/platform/external/avb/+/refs/tags/android-13.0.0_r15/avbtool.py#3121)).

`smuggle_descriptors` overrides the `AvbKernelCmdlineDescriptor` class with the `SmuggledViaKernelCmdlineDescriptor` class. The original `AvbKernelCmdlineDescriptor` takes in a kernel command line string and outputs the vbmeta binary representation of that string. The hacky `SmuggledViaKernelCmdlineDescriptor` takes in a preexisting descriptor object and outputs the binary representation of that descriptor object.

avbroot abuses this and calls

```python
avb.make_vbmeta_image(
    ...
    kernel_cmdlines = new_descriptors,
    ...
    include_descriptors_from_image = None,
    ...
)
```
 
to pass in the complete list of necessary descriptors (both the new ones for boot images and the original ones copied from the old vbmeta). Because the complete list is already provided via `kernel_cmdlines` and nothing is provided via `include_descriptors_from_image`, avbtool does not take the slow path of reading `.img` files itself and regenerating descriptors for every image.

**Comment by pascallj** [comment]
Thank you so much, this is very helpful! 

This gave me the confidence to try it on my Pixel 6a and it seems to work perfectly! Some notes below which might be interesting.

I had some trouble when relocking the bootloader, I got the error:

```FAILED (remote: 'invalid android images, skip locking')```

This might be because I tried to flash `boot.img`, `vendor_boot.img` and `vbmeta.img` to the other slot in attempt to try to test if I could still boot the original image in the current slot. However I realized the other slot also doesn't have the correct system (old OTA version) so this wouldn't work this time. Maybe it checks to see if the vbmeta data in both slots is correct before locking. Or maybe the version I installed via a incremental OTA in the current slot wasn't an exact match the full OTA from the website.

Either way by sideloading the full patched zip (and therefore switching slots) it allowed me to relock the bootloader and still boot (yellow triangle) without any issues.

Another thing to note is that locking the bootloader will also perform a factory reset. It is common knowledge that unlocking the bootloader will definitely wipe the data (which is the main purpose of locking it in the first place), but when relocking the bootloader the justification for wiping user data is less obvious (at least to me). Maybe it's useful to add this to the readme?

Also, in contrast to what I have read online, locking the bootloader, does not automatically disable OEM unlocking (at least not on my Pixel 6a). Of course this is a good thing, but still it might be useful to check afterwards if it is still enabled.

In an attempt to test if images signed with an built-in key would still boot, I flashed the same image to both slots however one slot with the original boot, vendor_boot and vbmeta, and one slot with the patched ones. Although I could perfectly boot both slots and have root in one and not in the other while being unlocked, I couldn't get the device to lock (same error as above) when the active slot was the original or when the patched slot wasn't the last succesfully booted slot (so I had to boot into the patched slot, reboot to bootloader, then lock).

Next, I tried to change the slot while booted into the patched one using the `bootctl` binary. Although I had to perform a factory reset to make the slot boot, I could actually boot the slot while still being locked! As you have mentioned, there is no way to return to the patched slot, now that I don't have root anymore. And just as before, after unlocking I couldn't relock. So I guess the bootloader can in fact boot both built-in and custom keys while being locked, but switching keys might force a reset anyway. Maybe the data partition is encrypted with the signature as well? This might also explain why a factory reset is necessary when locking.

Again, thanks a lot for this project and the detailed explanation and I will definitely keep an eye on this project.

**Comment by chenxiaolong** [comment]
Thanks for the thorough testing! That's interesting. So the bootloader does still have the Google key, but the bootloader cannot be locked unless vbmeta is signed with the custom key.

> Maybe the data partition is encrypted with the signature as well? This might also explain why a factory reset is necessary when locking.

Yep, I think that may be the case, though I don't think the signature is directly used to derive the data encryption key. I believe the TPM chip takes into account the vbmeta signing key hash, bootloader lock state, and OTA rollback numbers when determining if access to the key is allowed.

> when relocking the bootloader the justification for wiping user data is less obvious (at least to me).

I don't know the actual justification for this, but I'm guessing one of the reasons may be to reduce the chance of introducing hidden vulnerabilities. AOSP is pretty good about not loading things from `/data` in privileged processes. However, on Samsung devices, for example, there is (or used to be) a mechanism where SELinux policy updates could be delivered out-of-band. These would be stored in `/data` and loaded very early during boot. Without a forced factory reset, it'd be pretty trivial to weaken the security by doing something like:

1. unlock the bootloader
2. root the device
3. stop most of the running services (including GUI) and delete all files in `/data`
4. put a permissive SELinux policy in `/data`
5. flash the original OEM image
6. relock the bootloader (assuming no forced wipe)

On the next boot, verified boot would have a green status and it'd appear as if the device was factory reset, but there'd be a security hole.

> Maybe it's useful to add this to the readme?

Done! 15c951e320879bd1d78de30ad68d1951f6cea4de

**Comment by pascallj** [comment]
> Yep, I think that may be the case, though I don't think the signature is directly used to derive the data encryption key. I believe the TPM chip takes into account the vbmeta signing key hash, bootloader lock state, and OTA rollback numbers when determining if access to the key is allowed.

It doesn't have to be an exact match though, there is definitely some logic involved. If the bootloader is unlocked, the signing key hash is not a limiting factor. Also it is possible to update the rollback numbers without losing data as we have seen when upgrading from Android 12 to 13 recently.

> I don't know the actual justification for this, but I'm guessing one of the reasons may be to reduce the chance of introducing hidden vulnerabilities. AOSP is pretty good about not loading things from `/data` in privileged processes. However, on Samsung devices, for example, there is (or used to be) a mechanism where SELinux policy updates could be delivered out-of-band. These would be stored in `/data` and loaded very early during boot.

Ah, very interesting! In my opinion such updates should be signed so that exploit shouldn't be possible, but better to be safe than sorry I guess.
