### ISSUE TITLE
Patch Disable OEM Unlocking

### ISSUE THREAD

**Issue by landonbuttars** [chenxiaolong/avbroot#8]
Is there a way to patch the disable OEM unlocking UI button? It seems super risky to use software where one click of a button can render my $700 phone useless.

**Comment by chenxiaolong** [comment]
Android has several easy ways to disallow unchecking the option, but no way to disallow checking it. I think the only way to do this would be an LSPosed module.

**Comment by landonbuttars** [comment]
> Android has several easy ways to disallow checking the option, but no way to disallow unchecking it. I think the only way to do this would be an LSPosed module.
> 
> > It seems super risky to use software where one click of a button can render my $700 phone useless.
> 
> To clarify, the risk would be turning off OEM unlocking, maliciously/accidentally flashing an unpatched boot image, and then rebooting. Just turning off the option won't immediately brick the device.
> 
> EDIT: Actually, running:
> 
> ```shell
> resetprop ro.oem_unlock_supported 0
> ```
> 
> as root might be enough to remove the UI option. It should have no negative side effects with AOSP, but I don't know if that's the case with the Pixel stock ROM--there's a lot of proprietary stuff in there.

Thank you for the reply. 

Clarifying that unchecking alone won't brick the device is reassuring. It would require unchecking and flashing. 

I think it would still makes sense to disable the option all together but your response has addressed my concerns. 

Do you know if changing that prop also disables OEM unlocking?

**Comment by pascallj** [comment]
> Clarifying that unchecking alone won't brick the device is reassuring. It would require unchecking and flashing.

Well, if you really want to point it down, it does not necessarily have to be flashing. If you install some (malicious) piece of software which uses root, it can theoretically also screw up your installation (as is in the Readme).

However I think, that as long as you save your generated keys and certificates in safe location, and your recovery is still intact (but it is possible for software with root access to overwrite this), you can sideload another full OTA signed with your keys with this method. 

The only difference after using this method is who the system trusts to make modifications to the system. Normally, this is the OEM (Google in this case) and now this is you. The OEM pretty much guarantees that it never distributes an image which is so harmful to the system it cannot be recovered (and if it does, well at least this hard brick is now covered under warranty). Now, this is your job. This is also the reason why they put that switch in the UI only accessible via a booted system (instead of a bootloader command), so that you must be authenticated (system is verified and user is authenticated) before any modifications can be made.

That's why leaving the bootloader unlocked is generally considered safer because even if you screw up, in most cases you can still recover via fastboot. But not only you, everyone with physical access to the device. And because now there is no forced data wipe, as there is when changing from locked to unlocked or vice versa, anyone with physical access can in theory get access to the data by flashing a slightly modified image.

**Comment by landonbuttars** [comment]
>Well, if you really want to point it down, it does not necessarily have to be flashing. If you install some (malicious) piece of software which uses root, it can theoretically also screw up your installation (as is in the Readme).

This seems like an acceptable risk since whoever is trying to exploit the device would have to gain root access which would require either an exploit in Magisk or the user giving the malicious application root access. Theoretically, without unlocking the screen this should be very difficult. By the same point if someone unlocks your phone they have the data anyway. 

Additionally, this would have to be a targeted attack since they'd have to know you were running this version of rooted GrapheneOS. 

>That's why leaving the bootloader unlocked is generally considered safer (as protections against bricks) because even if you screw up, in most cases you can still recover via fastboot. 

To clarify, this is true even if you accidentally disable OEM unlocking in the UI? If I'm using Graphene as more of a privacy rom and less of a secure rom then this may be an acceptable compromise.

I appreciate your willingness to reply in detail about this. I wish there was more I could contribute but I'm not a mobile developer and this is some real impressive low level stuff.

**Comment by pascallj** [comment]
> This seems like an acceptable risk since whoever is trying to exploit the device would have to gain root access which would require either an exploit in Magisk or the user giving the malicious application root access. Theoretically, without unlocking the screen this should be very difficult. By the same point if someone unlocks your phone they have the data anyway.

If you're using just 'well-known' root tools and apps and doing nothing fancy, the risk in both cases (avbroot locked with the OEM-unlock-switch enabled or unlocked) the risk of bricking the device is very small. However the advantage of avbroot is that your system can't be modified without your knowledge. And if it is modified in any way, your data is wiped, so your data is secure.

> Additionally, this would have to be a targeted attack since they'd have to know you were running this version of rooted GrapheneOS.

I might be wrong, but the only usecase of avbroot is reduce the risk of targeted attack. An attacker must have physical access to your device to flash some partitions (unless malicious software is involved of course). If someone is going through the effort of trying to flash your device without your permission, I think you can safely assume that you're targeted.

> To clarify, this is true even if you accidentally disable OEM unlocking in the UI? If I'm using Graphene as more of a privacy rom and less of a secure rom then this may be an acceptable compromise.

When the bootloader is unlocked, this switch has no meaning and is disabled in the UI. If the bootloader is locked it is two-step process to unlock of both flipping the switch and unlocking in fastboot.

But this issue is something that has passed my mind as well when I was working with this project, but the setting is buried deep in developer settings, so I don't think there is much change of disabling it by accident. And of course the knowledge that unchecking it, doesn't result in a brick directly, but also needs a system so instable that you can't just simply enable it again for it to be bricked.

**Comment by avsprv** [comment]
A small offtop. Is it necessary to set a password when generating keys?

**Comment by pascallj** [comment]
An empty one is fine. It's just for your own security. If someone gets access to this file, they can sign updates for your specific device. If you have a password set as well, they also need the password. You can decide for yourself what security level fits your use case.

**Comment by Justwonderingmaybe** [comment]
Thanks for your input guys. Teamwork makes the dream work. I was wondering now that i could have root on my locked bootloader if i messed with some system files as i want to change the bootloader animation. Could i brick it? Or would i have to resign the /system/media/bootanimation_encrypted.zip with the priv avb key

**Comment by chenxiaolong** [comment]
If you modify the `/system` partition directly, the device very likely won't boot because root doesn't remove the dm-verity signature checks on `system`. I think you'd be much better off creating a Magisk module that replaces `/system/media/bootanimation_encrypted.zip` at runtime.

**Comment by Justwonderingmaybe** [comment]
Can anyone help me with that?

**Comment by chenxiaolong** [comment]
That's a bit off topic for this thread, but I'll include some pointers below. If you run into issues, I'd suggest asking in Magisk's own forums.

---

You can use this project's `clearotacerts` as an example. https://github.com/chenxiaolong/avbroot/tree/master/clearotacerts

A Magisk module is not much more than a zip file with a certain file structure. The zip needs `module.prop` (containing the module name, ID, description, etc.) and `META-INF/com/google/android` (which does not need to be changed). If you want to replace something in `/system`, you just put the files you want to replace in the `system` directory within the module's zip.

In your case, the contents of your zip file would be something like:
```
META-INF/com/google/android/update-binary
META-INF/com/google/android/updater-script
module.prop
system/media/bootanimation_encrypted.zip
```
