### ISSUE TITLE
Lost root / Magisk doesn't detect root

### ISSUE THREAD

**Issue by 1over137** [chenxiaolong/avbroot#91]
I have a Pixel 7 running GrapheneOS with root using this tool. After some updates, the Magisk app stopped working (I had used the hide app feature), so I deleted it. I had initially used an older version of the tool to install the OS and root, and it worked well for a long time. But when I forgot to update the tool first and patched the new OTA with new Magisk versions, the Magisk app no longer worked on the phone, but all the previously set up root apps continued working. I re-patched a new OTA properly, setting the Magisk preinit device, flashed it, and reinstalled the Magisk app on phone. While it opens, it does not seem to detect root. Other root apps continue to work. How to fix this?

**Comment by chenxiaolong** [comment]
Hmm, I've never seen that before. Just to rule out avbroot's patches causing this issue, can you give this a try?

1. Extract `init_boot.img` from the original GrapheneOS OTA:

    ```bash
    python avbroot.py \
        extract \
        --input /path/to/pather-ota_update-<date>.zip \
        --directory . \
        --boot-only
    ```

2. Patch the `init_boot.img` via Magisk's `Install` -> `Select and Patch a File` -> `init_boot.img`.

3. Grab the patched `/sdcard/Download/magisk_patched-<version>_<random letters>.img` from the device.

4. Run avbroot using that patched boot image:

    ```bash
    python avbroot.py \
        patch \
        --input /path/to/pather-ota_update-<date>.zip \
        --privkey-avb /path/to/avb.key \
        --privkey-ota /path/to/ota.key \
        --cert-ota /path/to/ota.crt \
        --prepatched magisk_patched-<version>_<random letters>.img
    ```

5. Flash the new patched OTA.

With this procedure, avbroot won't touch anything root-related. It just handles the signing steps. All the root-related patches are done by the Magisk app.

If you still run into the same issue after trying this, then you probably found a bug in Magisk. If that's the case, my only suggestion is to rename or delete `/data/adb`, which stores all the Magisk modules and Magisk configuration. Hopefully that gets you back to a clean state as if you installed Magisk for the first time.

**Comment by 1over137** [comment]
Thanks for the help. 
Using magisk to patch the image made no difference, so this probably isn't an issue with your tool. I used an app which still had root permissions to rename the directory and it seems to have restored Magisk to its original state. I would assume this happened due to one of the anti detection features.

**Comment by 1over137** [comment]
Hi, this seems to have happened again, and this time I do not have a root app to delete the folder. Is there some other way I can delete it without being able to access root directly on the device? I tried flashing a patched OTA with kernelSU but that does not work either

**Comment by pixincreate** [comment]
Just so you know, KernelSU is unsupported. You would have to compile kernel from scratch (and yes, I haven't tried avbroot with KernelSU. But highly likely, it is unsupported from the previous discussions).

Regarding Magisk, you may try latest debug / CI version which I believe is known to fix the issue of missing root.  
If you use terminal app like `Termux`, you can try executing `su` to get sudo access to `shell` after which you can try removing `/data/adb`.

Also, if you wish to have `Zygisk` running, you may try my version of [Magisk](https://github.com/pixincreate/Magisk) (Warning: It is a fork and not official one, I cannot guarantee support, or responsible for anything that may happen later on. This version gives you Zygisk at the cost of closed source modules like `Shamiko`) is known to work as I personally use it every single day.

**Comment by 1over137** [comment]
> KernelSU is unsupported

ok. The README page heavily implies it is though. After flashing it appears to be without any root. The `su` binary is now missing (before, it said permission denied) and it even passes Basic Integrity now.

What Magisk version do you mean? Do I need to compile it myself?

**Comment by pixincreate** [comment]
When was the last time you updated the OS? Asking so because, when GOS released QPR2 update, Magisk started to break. 

> The README page heavily implies it is though

Then I guess it works, not sure. However, LKM mode in KernelSU does not work as GrapheneOS enforces signature verification. Installing GKI results in bootloop as GrapheneOS heavily relies on stock kernel. It is always recommended to compile from scratch.

What do get when you try to execute `su` from termux? An error or a pop-up asking you to grant / deny root access?

Take Magisk from the latest CI, flash stock boot, patch stock boot image with Magisk, go to fastboot and execute `fastboot boot patched-boot.img`, see if you've root. If yes, install directly from Magisk installer.  

Yes, Zygisk will not work on official Magisk.

**Comment by 1over137** [comment]
> When was the last time you updated the OS

I'm not sure when it started to break but I suspect this has to do with the hidden magisk app somehow breaking and losing the ability to access root. 

> What do get when you try to execute su from termux

Sometimes it says Permission denied, sometimes it says nothing. In either case the return code is non-zero and I do not become root. No pop ups and no other errors.

Can I do that without unlocking the bootloader? I'm trying to first find a solution that doesn't involve unlocking as that would trigger a data wipe.

**Comment by pascallj** [comment]
Does the Magisk app still open? If so, what does it say when it's not detecting root? For example does it show anything under Logs?

Have you tried disabling all modules using [safe mode](https://topjohnwu.github.io/Magisk/faq.html#q-i-installed-a-module-and-it-bootlooped-my-device-help)?

Can you still access the Magisk binary from a non-root local terminal or adb shell: `magisk -c`, `magisk -v` etc.

Also be aware that the source of the Magisk used to patch the OTA and the Magisk APK must match. So if you have patched your OTA with the official Magisk APK, you must use the official Magisk APK. If you want to use APK in pixincreate's fork, you also have to patch your OTA with that Magisk APK. This is because:

> In release builds, the certificate of the key signing the Magisk APK will be used by Magisk’s root daemon as a reference to reject and forcefully uninstall any non-matching Magisk apps to protect users from malicious and unverified Magisk APKs. [link](https://topjohnwu.github.io/Magisk/build.html#signing-and-distribution)

If the latest debug / CI version is supposed to fix this issue, you must use this version of Magisk to patch your OTA in addition to installing this APK.

If in the end it really is a corruption in the `/data/adb` directory, I can't easily think of a way to access that directory without root. Maybe it is possible to compile Magisk yourself with a different `SECURE_DIR` so that it will use a different directory than `/data/adb` to store the files which will allow you to clean things up before you switch back to an official Magisk APK. That is however far beyond my experience with Magisk. Just a thought that crossed my mind.

**Comment by pixincreate** [comment]
> Can I do that without unlocking the bootloader? I'm trying to first find a solution that doesn't involve unlocking as that would trigger a data wipe.

I guess @chenxiaolong can help here as I, personally do not use avbroot given my time constraints but actively involved in.

But you try patching the build with magisk ci build of recent version because i've heard that fixing installation failure of magisk.

**Comment by chenxiaolong** [comment]
I would suggest trying @pascallj's suggestions, especially (1) ensuring the installed APK matches what was used to patch the OTA and (2) trying safe mode.

If `/data/adb` really did get corrupted somehow and it needs to be deleted, that is possible. We can hack in a boot script that wipes out the directory. But please try safe mode first.

---

Note that the latest Magisk CI builds since April will not work without https://github.com/chenxiaolong/avbroot/pull/268. This fix is not included in any released version of avbroot yet because Magisk's changes have not made it to a canary release.

---

Regarding KernelSU, it will never work properly with GrapheneOS unless you rebuild the GrapheneOS kernel with KernelSU's changes. The prebuilt GKI kernels distributed by KernelSU are not compatible with GrapheneOS.

The new LKM (Linux kernel module) installation method of KernelSU is also not compatible. As @pixincreate mentioned, GrapheneOS enforces kernel module signing and the KernelSU module is not signed by a key that GrapheneOS trusts.

(Additionally, the LKM is not supported by avbroot, even outside of GrapheneOS. This installation method relies on a closed source component (`ksuinit`) that runs on every boot with the highest possible userspace privileges. I have no interest in reverse engineering that binary and running/testing it my own devices.)

**Comment by 1over137** [comment]
The magisk app opens, but does not detect root (switching back to 27000). It says: Installed: N/A, Zygisk: No, Ramdisk: Yes

The magisk binary exists and is executable. 
```
panther:/ $ magisk -c
27.0:MAGISK:R (27000)
panther:/ $ magisk -V
27000
panther:/ $ magisk -v
27.0:MAGISK:R
```

[magisk_log_2024-06-05T08.34.38.log](https://github.com/user-attachments/files/15571740/magisk_log_2024-06-05T08.34.38.log)

Safe mode appears to run and reboots the device but it doesn't do anything useful, as the magisk app still isn't detecting root.

Interestingly it seems like the preinit device detected by magisk has changed at some point (from `persist` to `sda1`). I patched and flashed again but it made no difference.

**Comment by chenxiaolong** [comment]
> Interestingly it seems like the preinit device detected by magisk has changed at some point (from `persist` to `sda1`). I patched and flashed again but it made no difference.

Oh, that is super interesting. If I remember correctly, the Pixel 7 and 8 series have the same partitions. My 8 Pro has:
```
husky:/ # ls -l /dev/block/by-name/persist
lrwxrwxrwx 1 root root 15 2024-06-04 20:48 /dev/block/by-name/persist -> /dev/block/sda1
```
`persist` and `sda1` are likely the same. I'm guessing `magisk --preinit-device` also shows `persist`/`sda1`?

The fact that it picked `persist` at all is odd to me though. Every Pixel device I've had used `metadata` (`sda1`). Any chance you could give `--magisk-preinit-device metadata` a try?

**Comment by 1over137** [comment]
No effect. Root is now fully lost (even the apps which had root originally no longer works), but the `su` binary is still present.
Also on my device it says:
```
panther:/ $ ls -l /dev/block/by-name/metadata
lrwxrwxrwx 1 root root 15 2024-06-05 12:57 /dev/block/by-name/metadata -> /dev/block/sda8
```

**Comment by pixincreate** [comment]
Can you share the Magisk logs from `/cache/magisk.log` and /cache/magisk.log.bak` or better, check if that log contain any zygote signature errors? If yes, can you try my version of [Magisk](https://github.com/pixincreate/Magisk) and revert back?  

You would first have to install app.

**Comment by pascallj** [comment]
> Can you share the Magisk logs from `/cache/magisk.log` and /cache/magisk.log.bak` or better, check if that log contain any zygote signature errors?

I don't think these files are readable by a non-root user.

**Comment by 1over137** [comment]
The binary is present but I cannot use it (permission denied)

**Comment by pascallj** [comment]
Yes but as the Magisk 'Grant root' prompt doesn't show up, 1over137 is currently limited to apps which have currently 'Forever' root access. But as far as we know no terminal or file manager app has that.

**Comment by pixincreate** [comment]
Oh, got it. When I suffered the similar issue, I used to get pop-up asking to grant the app the permission.

**Comment by 1over137** [comment]
> 1over137 is currently limited to apps which have currently 'Forever' root access

This includes only AdAway, which can't really do anything. Also I'm not even sure that works anymore since I tried using safe mode.

**Comment by chenxiaolong** [comment]
You can try patching the OTA with this build of Magisk:

* APK: https://files.pub.chiller3.com/issues/avbroot/issue91/Magisk-c6f076251-dangerous-no-access-checks.apk
* Signature: https://files.pub.chiller3.com/issues/avbroot/issue91/Magisk-c6f076251-dangerous-no-access-checks.apk.sig (If you're interested in verifying the signature, follow the steps from avbroot's README. It's signed with the same key.)

It is built from https://github.com/topjohnwu/Magisk/commit/c6f076251033c46a66b8f06a517cd58d94ad2fb7 with the patch below. This completely disables all access checks when `su` is run from within `adb shell` (and adds a warning message every time `su` runs).

Hopefully that'll allow you to try to delete `/data/adb` and try out other things.

(If you need to use the Magisk app, you'll have to uninstall your existing one first because this build is signed with my key.)

```diff
diff --git a/native/src/core/su/su.cpp b/native/src/core/su/su.cpp
index 995d368f0..4ecdb5595 100644
--- a/native/src/core/su/su.cpp
+++ b/native/src/core/su/su.cpp
@@ -81,6 +81,8 @@ static void setup_sighandlers(void (*handler)(int)) {
 }
 
 int su_client_main(int argc, char *argv[]) {
+    fprintf(stderr, "WARNING: This build has no permission checks. Do not use after fixing underlying issue.\n");
+
     int c;
     struct option long_opts[] = {
             { "command",                required_argument,  nullptr, 'c' },
diff --git a/native/src/core/su/su_daemon.cpp b/native/src/core/su/su_daemon.cpp
index 6334e75d6..bd8f08954 100644
--- a/native/src/core/su/su_daemon.cpp
+++ b/native/src/core/su/su_daemon.cpp
@@ -86,7 +86,7 @@ void su_info::check_db() {
 }
 
 bool uid_granted_root(int uid) {
-    if (uid == AID_ROOT)
+    if (uid == AID_SHELL || uid == AID_ROOT)
         return true;
 
     db_settings cfg;
@@ -165,7 +165,7 @@ void prune_su_access() {
 }
 
 static shared_ptr<su_info> get_su_info(unsigned uid) {
-    if (uid == AID_ROOT) {
+    if (uid == AID_SHELL || uid == AID_ROOT) {
         auto info = make_shared<su_info>(uid);
         info->access = SILENT_SU_ACCESS;
         return info;
```

**Comment by 1over137** [comment]
phew, it worked. Thanks for the help. Magisk is working again after deleting the folder.

**Comment by chenxiaolong** [comment]
Great, glad to hear that worked!
